'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const cat=new Image(),human=new Image();cat.src='gigi.png';human.src='dordor.png';
const W=960,H=480,ground=390,px=175;
let state='ready',y=ground-76,vy=0,jumps=0,score=0,treats=0,lives=3,chaos=0,time=0,spawn=1,objects=[],boost=0,immune=0,last=0,world=0,flash=0;
const $=id=>document.getElementById(id);
function stats(){ $('score').textContent=Math.floor(score);$('treats').textContent=treats;$('lives').textContent=lives;$('chaos').textContent=chaos+'%';$('fill').style.width=chaos+'%';$('boost').disabled=state!=='running'||chaos<100||boost>0;$('pause').disabled=state==='ready'||state==='over';}
function show(title,detail,label){$('title').textContent=title;$('detail').textContent=detail;$('start').textContent=label;$('overlay').hidden=false;}
function start(){state='running';y=ground-76;vy=0;jumps=0;score=0;treats=0;lives=3;chaos=0;time=0;spawn=1.3;objects=[];boost=0;immune=0;world=0;flash=0;last=0;$('overlay').hidden=true;$('pause').textContent='Pause';$('notice').textContent='Gigi is on the loose!';stats();}
function jump(){if(state!=='running'||jumps>=2)return;vy=jumps===0?-650:-540;jumps++;}
function zoom(){if(state!=='running'||chaos<100||boost>0)return;chaos=0;boost=4;$('notice').textContent='ZOOMIES! Nothing can stop Boss Queen Gigi.';stats();}
function pause(){if(state==='running'){state='paused';show('Dordor needs a breather.','Your run is paused. Ready for more chaos?','Resume zoomies');$('pause').textContent='Resume';}else if(state==='paused'){state='running';last=0;$('overlay').hidden=true;$('pause').textContent='Pause';}stats();}
function end(){state='over';show(score>=1000?'Certified Zoomies Queen!':'Dordor caught you!',Math.floor(score)+' points · '+treats+' treats · '+Math.floor(time)+' seconds of chaos. Can you beat that?','Run again');$('notice').textContent='One tiny cat. One very tired human.';stats();}
function addObject(){const r=Math.random();if(r<.38){const high=Math.random()<.5;for(let i=0;i<3;i++)objects.push({kind:'treat',x:W+40+i*65,y:ground-(high?175:95),w:36,h:36});}else{const kind=r>.87?'dordor':r>.62?'box':'slipper';objects.push({kind,x:W+40,y:ground-(kind==='dordor'?112:kind==='box'?60:35),w:kind==='dordor'?65:60,h:kind==='dordor'?112:kind==='box'?60:35});}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function update(dt){if(state!=='running')return;time+=dt;const speed=330+Math.min(210,Math.floor(time/20)*35)+(boost>0?160:0);score+=dt*(boost>0?30:10);world+=speed*dt;immune=Math.max(0,immune-dt);flash=Math.max(0,flash-dt);const hadBoost=boost>0;boost=Math.max(0,boost-dt);if(hadBoost&&boost===0)$('notice').textContent='Zoomies cooled down. Keep collecting treats!';vy+=1700*dt;y+=vy*dt;if(y>=ground-76){y=ground-76;vy=0;jumps=0;}spawn-=dt;if(spawn<=0){addObject();spawn=1.25+Math.random()*.7;}const player={x:px+10,y:y+10,w:55,h:58};for(const o of objects){o.x-=speed*dt;if(!o.used&&hit(player,o)){o.used=true;if(o.kind==='treat'){treats++;score+=50;chaos=Math.min(100,chaos+20);if(chaos===100)$('notice').textContent='Chaos full! Tap Zoomies or press Z.';}else if(boost>0){score+=75;}else if(immune===0){lives--;immune=1.5;flash=.15;$('notice').textContent=lives>0?'Bonk! '+lives+' lives left. Keep jumping!':'Dordor finally gets some sleep.';if(lives<=0){end();break;}}}}objects=objects.filter(o=>o.x>-100&&!o.used);stats();}
function portrait(img,x,y,w,h){ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,14);ctx.clip();if(img.complete&&img.naturalWidth){if(img===cat)ctx.drawImage(img,320,60,600,730,x,y,w,h);else ctx.drawImage(img,340,0,510,875,x,y,w,h);}else{ctx.fillStyle='#8754c8';ctx.fillRect(x,y,w,h);}ctx.restore();ctx.strokeStyle=img===cat?'#cb9dff':'#cdf47b';ctx.lineWidth=3;ctx.strokeRect(x+1,y+1,w-2,h-2);}
function draw(){ctx.clearRect(0,0,W,H);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#17132e');grad.addColorStop(1,'#3a2856');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.fillStyle='#6c5384';ctx.font='bold 18px system-ui';ctx.fillText('3:00 AM',30,38);ctx.fillStyle='#a991c3';ctx.font='14px system-ui';ctx.fillText('LIVING ROOM · LEVEL '+(1+Math.floor(time/20)),30,62);ctx.globalAlpha=.12;for(let i=0;i<8;i++){const x=((i*160-world*.2)%1280+1280)%1280-100;ctx.fillStyle='#c2a2eb';ctx.fillRect(x,105,2,260);}ctx.globalAlpha=1;ctx.fillStyle='#483359';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#b58bcf';ctx.fillRect(0,ground,W,3);for(let i=0;i<15;i++){ctx.fillStyle='#705279';ctx.fillRect(((i*85-world)%1275+1275)%1275,ground+35,45,3);}ctx.font='45px system-ui';for(const o of objects){if(o.kind==='dordor')portrait(human,o.x,o.y,o.w,o.h);else{ctx.font=o.kind==='treat'?'32px system-ui':'46px system-ui';ctx.fillText(o.kind==='treat'?'🐟':o.kind==='box'?'📦':'🥿',o.x,o.y+o.h-4);}}if(boost>0){ctx.fillStyle='#c9f87c';ctx.globalAlpha=.55;for(let i=1;i<5;i++)ctx.fillRect(px-i*35,y+20,24,5);ctx.globalAlpha=1;}ctx.save();if(immune>0&&Math.floor(immune*12)%2===0)ctx.globalAlpha=.4;portrait(cat,px,y,76,76);ctx.restore();ctx.fillStyle='#eee0ff';ctx.font='bold 14px system-ui';ctx.fillText('GIGI',px+17,y-10);if(boost>0){ctx.fillStyle='#d4f68b';ctx.font='bold 25px system-ui';ctx.fillText('ZOOMIES! '+boost.toFixed(1)+'s',660,45);}if(flash>0){ctx.fillStyle='#ff638044';ctx.fillRect(0,0,W,H);}}
function frame(t){const dt=last?Math.min((t-last)/1000,.033):0;last=t;update(dt);draw();requestAnimationFrame(frame);}
$('start').addEventListener('click',()=>state==='paused'?pause():start());$('jump').addEventListener('pointerdown',e=>{e.preventDefault();jump();});canvas.addEventListener('pointerdown',e=>{e.preventDefault();jump();});$('boost').addEventListener('click',zoom);$('pause').addEventListener('click',pause);document.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON'&&e.code==='Space')return;if(['Space','ArrowUp','KeyZ','KeyP'].includes(e.code)){e.preventDefault();if(e.repeat)return;if(e.code==='KeyP')pause();else if(e.code==='KeyZ')zoom();else jump();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause();});stats();requestAnimationFrame(frame);
